# Generated by the mdview-review release workflow — do not edit by hand.
# Source template: .github/mdview.rb.tmpl in claude-code-tools/mdview-review
class Mdview < Formula
  desc "Markdown review in the browser with Approve / Request-changes buttons"
  homepage "https://github.com/claude-code-tools/mdview-review"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/claude-code-tools/mdview-review/releases/download/v0.1.2/mdview-darwin-arm64"
      sha256 "ecc47fa011eae16f6c3309565e438d2d0ecb5042f3536560753ab8544f90c029"
    end
    on_intel do
      url "https://github.com/claude-code-tools/mdview-review/releases/download/v0.1.2/mdview-darwin-amd64"
      sha256 "daf4c9f9463f56c39cc802ba959cfae5178e94929ec6447f375a11d86029bd9a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/claude-code-tools/mdview-review/releases/download/v0.1.2/mdview-linux-arm64"
      sha256 "6c9d84b0a14e229398faa5f937cac696cc08583cfb6c23588468768748eef676"
    end
    on_intel do
      url "https://github.com/claude-code-tools/mdview-review/releases/download/v0.1.2/mdview-linux-amd64"
      sha256 "d05a50860a10012c9d3c4fc19547ec4ab46412887f7855e4515729d480e30f15"
    end
  end

  def install
    # The release asset is the raw, per-platform binary; install it as `mdview`.
    bin.install Dir["mdview-*"].first => "mdview"
  end

  test do
    (testpath/"t.md").write("# hello\n")
    assert_match "mdview review", shell_output("#{bin}/mdview --print #{testpath}/t.md")
    assert_match "mdview", shell_output("#{bin}/mdview --version")
  end
end
