# Generated by the mdview-review release workflow — do not edit by hand.
# Source template: .github/mdview.rb.tmpl in claude-code-tools/mdview-review
class Mdview < Formula
  desc "Markdown review in the browser with Approve / Request-changes buttons"
  homepage "https://github.com/claude-code-tools/mdview-review"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/claude-code-tools/mdview-review/releases/download/v0.2.0/mdview-darwin-arm64"
      sha256 "d914af9fff4bf8211cf54657c3f059716efed88bd6d5d76ed821bcd49e906ef7"
    end
    on_intel do
      url "https://github.com/claude-code-tools/mdview-review/releases/download/v0.2.0/mdview-darwin-amd64"
      sha256 "09d794277e7926d05e716e87abdbbca97da140275e768a6331c0304f6ae917d8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/claude-code-tools/mdview-review/releases/download/v0.2.0/mdview-linux-arm64"
      sha256 "aaeae00af2a4204c64a6c0806229bd192976c8934bb98c3381cfdd1186c6f553"
    end
    on_intel do
      url "https://github.com/claude-code-tools/mdview-review/releases/download/v0.2.0/mdview-linux-amd64"
      sha256 "fe2f935e188fa2dac847db5e84f982e64d68d56686a6c8e33af2d495e4c809af"
    end
  end

  def install
    # The release asset is the raw, per-platform binary; install it as `mdview`.
    bin.install Dir["mdview-*"].first => "mdview"
  end

  test do
    (testpath/"t.md").write("# hello\n")
    assert_match "mdview review", shell_output("#{bin}/mdview --print #{testpath}/t.md")
    assert_match "mdview", shell_output("#{bin}/mdview --version")
  end
end
